version: '3'

services:
  game-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
      - "3001:3001"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SERVER_LOCATION=${RENDER_EXTERNAL_HOSTNAME:-localhost} # Use Render's URL or default to localhost
      - SERVER_PORT=${SERVER_PORT:-8100} # Default to 8100
      - WS_URL=${WS_URL:-ws://localhost:3001} # Default to ws://localhost:3001
    env_file:
      - .env
    # Optional volume mapping if you need persistent data
    # volumes:
    # Maybe good for logging so we can view logs outside of the container
    #   - ./logs:/app/logs
    #   - ./data:/app/data